[package]
name = "rustsbd"
version = "0.0.1-alpha.2"
edition = "2021"
authors = ["Val Andrei Fajardo <andrei@nerdai.io>", "Chi Ho Cheung <>"]
description = "Rust Sentence Boudnary Disambiguation"

[dependencies]
fancy-regex = "0.13.0"
rustsbd_macros = { path = "../rustsbd_macros" }